apiVersion: v1
kind: ConfigMap
metadata:
  name: search-service-config
  labels:
    app: search-service
data:
  # JVM 설정
  JVM_OPTS: "-Xms512m -Xmx768m -XX:+UseContainerSupport -XX:+UseG1GC -XX:MaxGCPauseMillis=200"
