# === dev 환경 네임스페이스 ===
apiVersion: v1
kind: Namespace
metadata:
  name: dev-user-service
---
apiVersion: v1
kind: Namespace
metadata:
  name: dev-community-service
---
apiVersion: v1
kind: Namespace
metadata:
  name: dev-match-service
---
apiVersion: v1
kind: Namespace
metadata:
  name: dev-search-service
---
apiVersion: v1
kind: Namespace
metadata:
  name: dev-twp-service
---
apiVersion: v1
kind: Namespace
metadata:
  name: dev-observability
---
apiVersion: v1
kind: Namespace
metadata:
  name: dev-gateway
---
apiVersion: v1
kind: Namespace
metadata:
  name: dev-db
