---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysql-config
  namespace: dev-db
spec:
  encryptedData:
    mysql-ip: AgB3UXOD9omk/4fod8+N4orzRpxNxzYPePLPpQgds8qRYGwYaajeADimye10U/m/U83vsb2wfxU8+y3DQFplrIcvLibJrrr0FLTahbxCzP0z5vdtSKIsqcEenha8KG3ap4Pg0LPeAz4MzC+t9do2p/1TxcK8QOZaatSophnYN6hOFrOoihrzrTq5XIgWFVfEDPowkrhqcgzva/9fR9h2TLBkYk6e66G8bdCJakSu2ro8SPrwj5HGKnnTes0FhdS+IZ9m/j84/k2H+lVbA+e6BM6HjZdsL6pu6U9N8dDSqy9DjYHbr1Kp6QO1yNo0StFvrNoFC2ge2f2YJYv0cq38mZI6/iOxOoJYOc6FQw842+EbWcp3aHZcPS3PbGU/CmQWy+GyJEIZasXmCHgZ//PyiDJDKNVmCx8qbyb4YmC9R67yMLIE3XYiZai8ngAV5xaHdGiQ1CkqsCLlHvSFgKzgRrKjEW1e4TGAIxr/66um0RN/bW9JLa+8Xb7T3pyBE7veCwG0hLyKbvyOh69m5jL6uTbK5rtF/8UAnOVE5p7D410i/k1OV87ngl4mcPQgo2sXDH43CfnsufbOvZw/9L4LG5cUMkNefTC8tGQHSDaqmd0or/QKP4QKByMMeomWuQt6hhNgQvSDTffnK+dxG2GimRQGUE/OL/JIzEyh8XpaL4eqL2RIlS+LiKLEZYYIFGngEqkYxZGr4OXYrCwe4CyD
  template:
    metadata:
      creationTimestamp: null
      name: mysql-config
      namespace: dev-db
    type: Opaque
