apiVersion: v1
kind: Service
metadata:
  name: community-service
  labels:
    app: community-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/actuator/prometheus"  # http://<pod-ip>:8080/actuator/prometheus
spec:
  selector:
    app: community-service
  ports:
    - port: 80
      targetPort: 8080
      name: http
  type: ClusterIP
