apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dev-redis-token
  namespace: dev-infra
spec:
  serviceName: "dev-redis-token"
  replicas: 3
  selector:
    matchLabels:
      app: dev-redis-token
  template:
    metadata:
      labels:
        app: dev-redis-token
    spec:
      containers:
        - name: redis
          image: redis:7.0-alpine
          command:
            - redis-server
            - "/redis-config/redis.conf"
          ports:
            - containerPort: 6379
              name: redis
            - containerPort: 16379   # 클러스터 노드 간 통신용 포트
              name: cluster
          volumeMounts:
            - name: redis-config
              mountPath: /redis-config
            - name: redis-data
              mountPath: /data
      volumes:
        - name: redis-config
          configMap:
            name: dev-redis-token-config
  volumeClaimTemplates:
    - metadata:
        name: redis-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 10Gi
