apiVersion: v1
kind: Service
metadata:
  name: dev-redis-token
  namespace: dev-infra
  labels:
    app: dev-redis-token
spec:
  clusterIP: None
  ports:
    - port: 6379
      name: redis
    - port: 16379
      name: cluster
  selector:
    app: dev-redis-token
