apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - gateway
  - overlays/develop/user-service
  - overlays/develop/match-service
  - overlays/develop/community-service
  - overlays/develop/search-service
  - overlays/develop/twp-service
  - shared/database
