apiVersion: apps/v1
kind: Deployment
metadata:
  name: match-service
spec:
  template:
    spec:
      containers:
        - name: match-service
          image: chunsam.kr-central-2.kcr.dev/playus-match-service/match-service:13-a509070
