# ingress 설정
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kong-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: api.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dev-kong-proxy
                port:
                  number: 80
    - host: kong-admin.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dev-kong-cp-admin
                port:
                  number: 8002
          - path: /admin-api
            pathType: Prefix
            backend:
              service:
                name: dev-kong-cp-admin
                port:
                  number: 8001
