apiVersion: v1
kind: Service
metadata:
  name: dev-mongo-read
  namespace: dev-infra
spec:
  type: ClusterIP
  ports:
    - port: 27017
      targetPort: 27017
---
apiVersion: v1
kind: Endpoints
metadata:
  name: dev-mongo-read
  namespace: dev-infra
subsets:
  - addresses:
      - ip: 129.154.50.74
    ports:
      - port: 27017
