apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: yukyung0/playus-user-service:latest
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: JAVA_OPTS
              valueFrom:
                configMapKeyRef:
                  name: user-service-config
                  key: JVM_OPTS
            - name: JAVA_TOOL_OPTIONS
              valueFrom:
                configMapKeyRef:
                  name: user-service-config
                  key: JVM_OPTS
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 180
            periodSeconds: 10
            timeoutSeconds: 10        # 타임아웃 늘림
            failureThreshold: 6
            successThreshold: 1
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 200
            periodSeconds: 30
            timeoutSeconds: 10        # 타임아웃 늘림
            failureThreshold: 3
          # 시작 프로브 추가
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 90
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 30      # 최대 5분
            successThreshold: 1
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sleep", "15"]
          resources:
            requests:
              cpu: "300m"
              memory: "512Mi"
            limits:
              cpu: "600m"
              memory: "1Gi"
      terminationGracePeriodSeconds: 45
