---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mongo-read-config
  namespace: dev-db
spec:
  encryptedData:
    mongo-read-ip: AgCeXIGWBy2sI/jNcg7f3w+0HP7kQ5lwb5n0IgpZST3h3JULaUJNJee7t+H/SPQ7TsIbPDl8yzqw46jWYeVgkPDZ7gaU1NBGrGUh3AcRBKZUqonG7GRrVZ8T20t25kOfWCIhBGI9iQGwMY/NY8MMjx4iorKco7eOgDA5oWXYVDszc5a4FnCjsubUXcYPP4Td41x79grBP3lhW2U9vU71BBSLEmYvOXzomNkWlXYbcGIA/uynzCV0payx2rOAJQdNolx87B3q/ca3gLi0BrGULKSbJHCjswQprm14xVhq4VKmxYHyTJw8MukLHsH1QddLUU+kkw2zaP42/nwhXWA7/akGAULIzchr1AgO/GVjO+UgcSK/kDmRoItMPoYgLQ360aY68RFQ/+jPkhnRD9XrpXlKwyGI2gbULh51HqD5GWHK4dXkIu3YV4a8EEKNhK10dKLYuDn8ug7Dj+zMr/1ujYhi2qzFHdceslehTuKg+bfjWWLELbRH3eibfxpuuPtXeuVEFkSYfFL/Wmo859cRZOsErHk/nHFmDhj1xSvuZe2rYNgkAQvFczc3mAzq3f02D6Yt2ULrrQ1RJ2TxBpnlpRMstsQDD127CrneH23pvUxWlDE5xU/zXyIPuC/QRKdA9wtqyw5PiipX47WI5tQsIxmGTb4SA8pzpAB6dedy8kRqgmCBo0T8FcxBEZMhZpiIMoL4QHwyLPErDWtgiczx
  template:
    metadata:
      creationTimestamp: null
      name: mongo-read-config
      namespace: dev-db
    type: Opaque
