apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev-db

resources:
  - dev-redis-cluster-init-job.yaml
  - dev-redis-configmap.yaml
  - dev-redis-service.yaml
  - dev-redis-stateful.yaml
