apiVersion: v1
kind: Service
metadata:
  name: onpremise-mysql
  namespace: user-service
spec:
  ports:
    - port: 3306
      targetPort: 3306
---
apiVersion: v1
kind: Endpoints
metadata:
  name: onpremise-mysql
  namespace: user-service
subsets:
  - addresses:
      - ip: 129.154.50.74  # 온프레미스 DB 서버 IP
    ports:
      - port: 3306