# 기본 값 설정
namespace: default
host: localhost
stripPath: "false"
pathType: Prefix

# 서비스 기본 설정
service:
  name: default-service
  port: 80

path: /
customAnnotations: {}

# Slack Webhook 프록시 관련 기본값
slackWebhook:
  enabled: false  # values-dev에서 개별적으로 true 설정
  host: "hooks.slack.com"
  path: "/slack/webhook"
  servicePort: 443
  corsEnabled: true
  stripPath: false
