---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mongo-chat-config
  namespace: dev-db
spec:
  encryptedData:
    mongo-chat-ip: AgB1jCR2DGm+sqdilehVfgH8RDvy3JgOvjISvPzdLEFBdQRYq7T/tjFngDAok14I/1vWZGELQstVatd5ZxypRtqlYXjWabdIATdEGDTl169OlH0/yJqyDh7nfTarQc/N5ua+JmoCowLnLaA0UBKHuMgLnyv9lNrrd4dipqosjn9Pl8CjsVx0PoEEJWpYH/MnhC3ecygN/Gv0cTsqgVw66yfg1+VRRWmwyaTsEzujc0OVqLjcyc39kQXfh2s3QSnUX1/wBMPA8KXF5CfVTkK76yeyMcij2SNfGRWovBnhitbNNcLT8NUzgZz+HlOue6hqTqaUaYZR/bgwSqfC0ANoPT8ASPY8bUkiNPYOFAgp7gVCEtgCnGpFLZCVL3PLQaccQtcYkww2eqi2aUnE46uiKn2ED0V/bmQa075A5pMJfmbha2O/1AJpeQQ1/wwoA4zQ6YN9CMnb3sFJX9zAZ8rnEU3EQUiMGHW8/EGuf2+hrq8NyEMxJPO1yCVZfNywelvQTJbjznm2HdsMC89+O1S2DU142U/D91y6/KxzI2uuq5FfVLuABAYiHBBImaloyZEqUD7I0jYMW9xuFtfS1+03Kil6eBVor2WQWHg1HUGUxleOJ4z51JoP+6c9Ac0YoGsY1AKy9TplID7GyU9XbDukS3hENgtpZin4iDE0yXz7O1gVSp13kiV2tq1Br/Ud/NX7bAc6jBpl74X0UXiHYHci
  template:
    metadata:
      creationTimestamp: null
      name: mongo-chat-config
      namespace: dev-db
    type: Opaque
