apiVersion: v1
kind: Service
metadata:
  name: match-service
  labels:
    app: match-service
spec:
  selector:
    app: match-service
  ports:
    - port: 80
      targetPort: 8080
      name: http
  type: ClusterIP
