# templates/ingress.yaml
{{- range $serviceName, $config := .Values.services }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $serviceName }}-ingress
  namespace: {{ $config.namespace }}
  annotations:
    kubernetes.io/ingress.class: kong
    {{- if $config.stripPath | default $.Values.stripPath }}
    konghq.com/strip-path: "true"
    {{- end }}
    {{- if $config.annotations }}
    {{- toYaml $config.annotations | nindent 4 }}
    {{- end }}
    {{- if $config.customAnnotations }}
    {{- toYaml $config.customAnnotations | nindent 4 }}
    {{- end }}
spec:
  rules:
  {{- if $config.host }}
    - host: {{ $config.host }}
      http:
        paths:
      {{- range $config.paths }}
          - path: {{ .path }}
            pathType: {{ $config.pathType | default $.Values.pathType | default "ImplementationSpecific" }}
            backend:
              service:
                name: {{ $config.service.name }}
                port:
                  number: {{ $config.service.port }}
      {{- end }}
  {{- else }}
    - http:
        paths:
      {{- range $config.paths }}
          - path: {{ .path }}
            pathType: {{ $config.pathType | default $.Values.pathType | default "ImplementationSpecific" }}
            backend:
              service:
                name: {{ $config.service.name }}
                port:
                  number: {{ $config.service.port }}
      {{- end }}
  {{- end }}
{{- end }}
