apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "kong-ingress.name" . }}
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: kong
    {{- if .Values.host }}
    kubernetes.io/ingress.host: {{ .Values.host }}
    {{- end }}
    {{- if .Values.stripPath }}
    konghq.com/strip-path: "true"
    {{- end }}
    {{- with .Values.customAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  rules:
    {{- if .Values.host }}
    - host: {{ .Values.host }}
      http:
        paths:
          {{- range .Values.paths }}
          - path: {{ .path }}
            pathType: {{ $.Values.pathType }}
            backend:
              service:
                name: {{ $.Values.service.name }}
                port:
                  number: {{ $.Values.service.port }}
          {{- end }}
    {{- else }}
    - http:
        paths:
          {{- range .Values.paths }}
          - path: {{ .path }}
            pathType: {{ $.Values.pathType }}
            backend:
              service:
                name: {{ $.Values.service.name }}
                port:
                  number: {{ $.Values.service.port }}
          {{- end }}
    {{- end }} 
          