{{- if .Values.slackWebhook.enabled }}
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: cors-slack-webhook
  namespace: {{ .Values.namespace | default .Release.Namespace }}
plugin: cors
config:
  origins:
  {{- range .Values.slackWebhook.cors.origins }}
    - {{ . | quote }}
  {{- end }}
  methods:
  {{- range .Values.slackWebhook.cors.methods }}
    - {{ . | quote }}
  {{- end }}
  headers:
  {{- range .Values.slackWebhook.cors.headers }}
    - {{ . | quote }}
  {{- end }}
  credentials: {{ .Values.slackWebhook.cors.credentials }}
  preflight_continue: {{ .Values.slackWebhook.cors.preflightContinue }}
  max_age: 3600
---
apiVersion: configuration.konghq.com/v1
kind: KongService
metadata:
  name: slack-webhook-service
  namespace: {{ .Values.namespace | default .Release.Namespace }}
spec:
  url: {{ .Values.slackWebhook.service.url }}
---
apiVersion: configuration.konghq.com/v1
kind: KongRoute
metadata:
  name: slack-webhook-route
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  annotations:
    konghq.com/plugins: cors-slack-webhook
spec:
  protocols:
    - https
    - http
  paths:
    - {{ .Values.slackWebhook.path | default .Values.path }}
  methods:
    - POST
    - OPTIONS
  strip_path: {{ .Values.stripPath | default false }}
  preserve_host: true
  https_redirect_status_code: 308
  hosts:
    - {{ .Values.slackWebhook.host | default .Values.host | quote }}
  service: slack-webhook-service
{{- end }}
