{{- if .Values.slackWebhook.enabled }}
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: slack-webhook-cors
  namespace: {{ .Release.Namespace }}
plugin: cors
config:
  origins:
    - "*"
  methods:
    - POST
    - OPTIONS
  headers:
    - Content-Type
  exposed_headers:
    - Custom-Header
  credentials: false
  max_age: 3600
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: slack-webhook-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: kong
    konghq.com/plugins: slack-webhook-cors
    konghq.com/protocols: https
    konghq.com/preserve-host: "false"
    konghq.com/host-header: "hooks.slack.com"
    # 여기서 직접 웹훅 URL로 연결합니다
    konghq.com/path: "/services/T08H7N433M2/B08RY01LU2G/8lopFWaitZlEnyQPNsFxfRwl"
spec:
  rules:
    - http:
        paths:
          - path: {{ .Values.slackWebhook.path }}
            pathType: Prefix
            backend:
              service:
                name: slack-webhook-service
                port:
                  number: 443
---
# Kong에서 외부 서비스로 직접 연결하는 서비스
apiVersion: v1
kind: Service
metadata:
  name: slack-webhook-service
  namespace: {{ .Release.Namespace }}
spec:
  type: ExternalName
  externalName: hooks.slack.com
  ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 443
{{- end }}
