apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev-monitoring

resources:
  - ../../../base/monitoring
  - patch-prometheus-config.yaml
  - patch-prometheus-config.yaml
  - patch-promtail-config.yaml
  - patch-rbac.yaml
