apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: twp-service-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: twp-service
  minReplicas: 2        # 최소 pod 개수
  maxReplicas: 4        # 최대 pod 개수
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
    - type: Resource
      resource:
          name: memory
          target:
            type: Utilization
            averageUtilization: 70
