apiVersion: v1
kind: Service
metadata:
  name: dev-elasticsearch
spec:
  type: ClusterIP
  ports:
    - port: 9200
      targetPort: 9200
---
apiVersion: v1
kind: Endpoints
metadata:
  name: dev-elasticsearch
  namespace: dev-db
subsets:
  - addresses:
      - ip: 0.0.0.0     # 외부 DB IP 주소 설정
    ports:
      - port: 9200
      