---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: elasticsearch-config
  namespace: dev-db
spec:
  encryptedData:
    elasticsearch-ip: AgABT4QoSRWII41v4jO+rcC8i+w/fBP4J/qk6R2Zh2NSoXKl8xXTdVGC48HQBrCUG/K6ReQV9tPoi4r5juSgF/ffQHQx69P/jl6C/dEIaqPgNyEwnWyWevAGAdSrTzqmV5dRFIeSRMgknZdp00NMD0w613m5wt52KyTex/J80r356ptqGDq83VkE+K2pPbiShsX0bwfoSrkr/rWLVfK5pjH7mUeTW14gMhede/JbrPdlrDuf/FhEIiM9Uu3octM1ouTKfDEocMWn6b2/kMn4DDXHZnQZcx6GElPhUteCJJYmnXhpMf0W8KWshjkB8HGgFVVfLyXlO4Ww+yeE0Tsmg1hsh2jjyQM9Ih1yOV1a0NLcgbtnfJHLN6g00/gncSO2Ry9KxQD938XElTyNOWk2IrIamrLygKHMLrU+8JBbHv9F/SjHmI9e/aBltXeFJIz4Jj052yPhRWIT4mTstEB574R119YpsxkTPTgCBs0POVOAkDdlLiuXnI9V4HsqqvPYKgq1GCGXHokEiIzAQdGYaHLvtjFzRouRVaW+297dW+zLddh71J8l9b6svGcabgGEMso0u+gwU4Z06ZgB5yr517yPyIssZQLaWRgBbwNWL7jMSGNYQ6VtYkqLd5m+mvmkbJi+EJb1ImDs3sDNfmK3f/xnrX4PQOb4EpOf+5+lNz16YvAhKn2+ZvP+zgchlEx4S4gg3KynGcPQ8ipVeBYJ
  template:
    metadata:
      creationTimestamp: null
      name: elasticsearch-config
      namespace: dev-db
    type: Opaque
