---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: elasticsearch-config
  namespace: dev-db
spec:
  encryptedData:
    elasticsearch-ip: AgB5WjWiK6NkS9ytHb5ib8rUFMKdkLGaYeSieMaAGbbszDdCPklWfo6FuBp24x31GXV90c6xGvj47yqGSa28/QpLiPLN0mDPpBLBBN/wWe4qPfnCZXV0WL5mlI6OXlllk4HNMMVzIrQnwK8p2JGdi+EFtYuBysris2SIgTaOhejPnEStJr8YuW/19u2P9IL/KMl2XfUmgq2Qgz5UaRhyBUsf5YNBsGORSHAcDCcdiq5so017xan8/IUIBo3e+tyM10kd9WVRbcDk5ZvFo+EG2Vg4uNOPIHZ/lTDs4JcYQGz/wu+eVOLkrmSf8QGCeigXCqaMZw9e6UaJt2j32SDC56YsX6H0lDkXXdh/0qfrxQP48DXtFMkD1lFa7+AvdTb2NwS1dciVrZrB3WNEY+Kz/SFoGPU/b2R/WxaigSxVF9BD27ywHXzKpdry36UF+LFNl0T62cDBm0IFG6B3eNk2AxoEIKfwbU+JPiN0v3p2136P7Gh7qVycd6OPJ9oLDiaNPDTEi1FmeiDUqScu/7RdnrXlRlBcQliBOYyq9fbFb066/TUwFcM1n7JVbpvDPa3U+X6fXs5niq4xQMajWqDeqtnsqaRZpvNcAWdtHalyeVHVgflJG8K3iAe0QbBevpb7TXmoO8RP/DNppgx7PQD7f6ruNf8Ft9WTqxYIf0tuS+OAnwoLHTNySVt74MGhdMDLgum2ykjYvlvGttoy92Bn
  template:
    metadata:
      creationTimestamp: null
      name: elasticsearch-config
      namespace: dev-db
    type: Opaque
