# twp-service 네임스페이스의 DB 연결 정보(Sealed Secret)를 관리하는 ArgoCD 애플리케이션 설정입니다.
# overlays/develop/user-service/twp-secret 경로에 있는 Sealed Secret 파일을 배포 대상으로 삼습니다.
# kubectl apply -f dev-twp-db-secret-application.yaml -n argocd

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-twp-db-secret
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/KEA-ChunSam/PlayUs-k8s.git
    targetRevision: HEAD
    path: overlays/develop/twp-service/sealed-secret
  destination:
    server: https://kubernetes.default.svc
    namespace: dev-twp-service
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
