# match-service 네임스페이스의 서비스 리소스를 관리하는 ArgoCD 애플리케이션 설정입니다.
# kubectl apply -f dev-match-service-application.yaml -n argocd

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-match-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/KEA-ChunSam/PlayUs-k8s.git
    targetRevision: HEAD
    path: overlays/develop/match-service
  destination:
    server: https://kubernetes.default.svc
    namespace: dev-match-service
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
