apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev-database-applicationset
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: dev-mysql
            path: shared/database/mysql
            namespace: dev-db
          - name: dev-mongo-chat
            path: shared/database/mongo-chat
            namespace: dev-db
          - name: dev-mongo-read
            path: shared/database/mongo-read
            namespace: dev-db
          - name: dev-elasticsearch
            path: shared/database/elasticsearch
            namespace: dev-db
          - name: dev-redis-token
            path: shared/database/redis-token
            namespace: dev-db
          - name: postgres-kong
            path: shared/database/postgres-kong
            namespace: dev-db
  template:
    metadata:
      name: '{{name}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/KEA-ChunSam/PlayUs-k8s.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
