# kubectl apply -k argocd/ -n argocd

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - dev-community-service-application.yaml
  - dev-match-service-application.yaml
  - dev-search-service-application.yaml
  - dev-twp-service-application.yaml
  - dev-user-service-application.yaml
  - dev-infra-db-application.yaml
  - dev-monitoring-application.yaml
