# user-service 네임스페이스의 DB 연결 정보(Sealed Secret)를 관리하는 ArgoCD 애플리케이션 설정입니다.
# overlays/develop/user-service/sealed-secret 경로에 있는 Sealed Secret 파일을 배포 대상으로 삼습니다.

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-user-db-secret
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/KEA-ChunSam/PlayUs-k8s.git
    targetRevision: HEAD
    path: overlays/develop/user-service/sealed-secret  # 새로 만든 디렉토리
  destination:
    server: https://kubernetes.default.svc
    namespace: user-service
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
