apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  type: NodePort
  ports:
    - port: 9090          # 서비스 포트 (내부)
      targetPort: 9090    # 컨테이너 포트 (Prometheus 기본)
      nodePort: 30090     # 외부 접근 포트
  selector:
    app: prometheus
