apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - sealed-secret.yaml
  - ../../../base/match-service

patches:
  - path: patch-image.yaml
  - path: patch-env.yaml

namespace: prod-match-service

generatorOptions:
  disableNameSuffixHash: true
