apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/user-service
  - ../../../shared/database

patches:
  - path: patch-image.yaml
  - path: endpoint-dev.yaml

secretGenerator:
  - name: user-db-secret
    envs:
      - ../../../secrets/user-db-secret.env
    namespace: user-service

generatorOptions:
  disableNameSuffixHash: true

namePrefix: dev-
