apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/user-service
  - sealed-secret.yaml

patches:
  - path: patch-image.yaml

#secretGenerator:
#  - name: user-db-secret
#    envs:
#      - .env.secret
#    namespace: user-service

generatorOptions:
  disableNameSuffixHash: true

namePrefix: dev-
