apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - sealed-secret.yaml
  - ../../../base/user-service

patches:
  - path: patch-image.yaml

namespace: dev-user-service

generatorOptions:
  disableNameSuffixHash: true
