apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/search-service

patches:
  - path: patch-image.yaml

secretGenerator:
  - name: search-db-secret
    envs:
      - .env.secret
    namespace: search-service

generatorOptions:
  disableNameSuffixHash: true

namePrefix: dev-
