apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-service
spec:
  template:
    spec:
      containers:
        - name: search-service
          image: yukyung0/playus-search-service:11-f734c55
