apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - sealed-secret.yaml
  - ../../../base/community-service

patches:
  - path: patch-image.yaml

namespace: dev-community-service

generatorOptions:
  disableNameSuffixHash: true
