apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/community-service

patches:
  - path: patch-image.yaml

generatorOptions:
  disableNameSuffixHash: true

namePrefix: dev-
