apiVersion: v1
kind: Namespace
metadata:
  name: community-service
---
apiVersion: v1
kind: Namespace
metadata:
  name: match-service
---
apiVersion: v1
kind: Namespace
metadata:
  name: search-service
---
apiVersion: v1
kind: Namespace
metadata:
  name: twp-service
---
apiVersion: v1
kind: Namespace
metadata:
  name: user-service
