apiVersion: v1
kind: Namespace
metadata:
  name: community-service
---
apiVersion: v1
kind: Namespace
metadata:
  name: match-service
---
apiVersion: v1
kind: Namespace
metadata:
  name: search-service
---
apiVersion: v1
kind: Namespace
metadata:
  name: twp-service
---
apiVersion: v1
kind: Namespace
metadata:
  name: user-service
---

# 인프라 시스템
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: v1
kind: Namespace
metadata:
  name: logging
---
apiVersion: v1
kind: Namespace
metadata:
  name: infra
