# base/kong-gateway/kong-dp-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong-dp
  labels:
    app: kong-dp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kong-dp
  template:
    metadata:
      labels:
        app: kong-dp
    spec:
      containers:
        - name: kong
          image: kong:3.4.0
          env:
            - name: KONG_CLUSTER_CERT
              value: /etc/secrets/kong-cluster-cert/tls.crt
            - name: KONG_CLUSTER_CERT_KEY
              value: /etc/secrets/kong-cluster-cert/tls.key
            - name: KONG_ROLE
              value: "data_plane"
            - name: KONG_DATABASE
              value: "off"
            - name: KONG_CLUSTER_CONTROL_PLANE
              value: "kong-cp-cluster:8005"
            - name: KONG_PROXY_LISTEN
              value: "0.0.0.0:8000"
            - name: KONG_PROXY_LISTEN_SSL
              value: "0.0.0.0:8443"
          volumeMounts:
            - name: kong-cluster-cert
              mountPath: /etc/secrets/kong-cluster-cert
              readOnly: true
          ports:
            - containerPort: 8000
              name: proxy
            - containerPort: 8443
              name: proxy-ssl
      volumes:
        - name: kong-cluster-cert
          secret:
            secretName: kong-cluster-cert
