# base/kong-gateway/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - kong-cp-deployment.yaml
  - kong-dp-deployment.yaml
  - kong-cp-service.yaml
  - kong-proxy-service.yaml
  - kong-init-job.yaml
  #- kong-config.yaml

configMapGenerator:
  - name: kong-declarative-config
    files:
      - kong.yaml
