# shared/database/postgres-kong/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev-db

resources:
  - prod-postgres-deployment.yaml
  - prod-postgres-service.yaml
  - prod-postgres-pvc.yaml
