# shared/database/postgres-kong/postgres-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-kong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-kong
  template:
    metadata:
      labels:
        app: postgres-kong
    spec:
      containers:
        - name: postgres
          image: postgres:13
          env:
            - name: POSTGRES_HOST
              value: dev-postgres-kong
            - name: POSTGRES_USER
              value: kong
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kong-secrets
                  key: postgres-password
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -h
                - localhost
                - -U
                - kong
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-kong-pvc
