apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-kong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-kong
  template:
    metadata:
      labels:
        app: postgres-kong
    spec:
      containers:
        - name: postgres-kong
          image: postgres:13
          env:
            - name: POSTGRES_USER
              value: kong
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secrets-kong
                  key: postgres-password
            - name: POSTGRES_DB
              value: kong
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc-kong
