apiVersion: v1
kind: Secret
metadata:
  name: user-db-credentials
  namespace: user-service
type: Opaque
data:
  url: amRiYzpteXNxbDovLzE3Mi4xNi4yMTEuMzY6MzMwNi91c2Vy  # jdbc:mysql://172.16.211.36:3306/user
  username: cm9vdA==  # root
  password: MTIzNA==  # 1234